# Generated by Django 5.0.6 on 2025-11-07 06:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FSSAIEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fssai_code', models.CharField(max_length=100)),
                ('authorisation_name', models.CharField(max_length=150)),
                ('date_of_delivery', models.DateField()),
                ('number_of_orders', models.PositiveIntegerField()),
                ('logo', models.ImageField(upload_to='logos/')),
                ('certificate', models.FileField(upload_to='certificates/')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('feedback', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='bottle.fssaientry')),
            ],
        ),
    ]
